"""Add TRAMITE and SENTENCIA to Movimiento.tipo enum

Revision ID: 233e8897dfc4
Revises:
Create Date: 2025-11-10 21:20:21.271077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '233e8897dfc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Documento', 'tipo',
               existing_type=mysql.ENUM('RESOLUCIÓN', 'OFICIO', 'PRUEBA', 'OTRO'),
               type_=sa.Enum('RESOLUCIÓN', 'OFICIO', 'PRUEBA', 'OTRO', name='tipo_documento'),
               existing_nullable=False)
    op.alter_column('Notificacion', 'estado',
               existing_type=mysql.ENUM('PENDIENTE', 'ENVIADA', 'LEÍDA', 'ERROR'),
               type_=sa.Enum('PENDIENTE', 'ENVIADA', 'LEÍDA', 'ERROR', name='estado_notificacion'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDIENTE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Notificacion', 'estado',
               existing_type=sa.Enum('PENDIENTE', 'ENVIADA', 'LEÍDA', 'ERROR', name='estado_notificacion'),
               type_=mysql.ENUM('PENDIENTE', 'ENVIADA', 'LEÍDA', 'ERROR'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.alter_column('Documento', 'tipo',
               existing_type=sa.Enum('RESOLUCIÓN', 'OFICIO', 'PRUEBA', 'OTRO', name='tipo_documento'),
               type_=mysql.ENUM('RESOLUCIÓN', 'OFICIO', 'PRUEBA', 'OTRO'),
               existing_nullable=False)
    # ### end Alembic commands ###